# Generated by Django 5.2.4 on 2025-10-27 23:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMININO', 'Feminino')], max_length=10)),
                ('categoria', models.CharField(choices=[('AMADOR', 'Amador'), ('INTERMEDIARIO', 'Intermediário'), ('PROFISSIONAL', 'Profissional')], max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('auth_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('EM_ADESAO', 'Em Adesão'), ('COMPLETA', 'Completa'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada')], default='EM_ADESAO', max_length=10)),
                ('local_descricao', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField()),
                ('categoria', models.CharField(choices=[('AMADOR', 'Amador'), ('INTERMEDIARIO', 'Intermediário'), ('PROFISSIONAL', 'Profissional')], max_length=15)),
                ('tipo', models.CharField(choices=[('MASCULINA', 'Masculina'), ('FEMININA', 'Feminina'), ('MISTA', 'Mista')], max_length=10)),
                ('jogadores_confirmados', models.ManyToManyField(blank=True, related_name='partidas_confirmadas', to='api.jogador')),
                ('jogadores_pendentes', models.ManyToManyField(blank=True, related_name='partidas_pendentes', to='api.jogador')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_criadas', to='api.jogador')),
            ],
        ),
    ]
